Added animation
Rubix98/algoview pull request #53
Opened 2023-03-20 21:38 UTC by imaTik0

Nie jestem do końca pewien tego gdzie powinienem umieścić zmienne animationInterval i animationDelay. Próbowałem dodać przyciski do ustawienia prędkości ale brzydko to wyglądało, zostaje za to miejsce na mini taska.

2023-03-21 11:35 UTC, xenix1337 requested changes

2023-03-21 11:35 UTC, xenix1337 commented on frontend/src/components/mainPage/scene/subcomponents/NavigationPanel.vue
> +                var intervalID = window.setInterval(
Możemy wywołać setInterval a następnie demontować obiekt NavigationPanel. W unmounted należy rzucić clearInterval

2023-03-21 11:35 UTC, xenix1337 commented on frontend/src/components/mainPage/scene/subcomponents/NavigationPanel.vue
> +    let animationDelay = 500;
To do data()

2023-03-21 11:38 UTC, xenix1337 commented on frontend/src/components/mainPage/scene/subcomponents/NavigationPanel.vue
> +                                animationInterval = false;
Większy sens miałoby = null

2023-03-22 21:01 UTC, Rubix98 commented on frontend/src/components/mainPage/scene/subcomponents/NavigationPanel.vue
> +                                clearInterval(this.animationInterval);
Te 2 operacje chcemy zawsze wykonywać razem, dlatego proponuję przenieść to do osobnej funkcji i podpiąć tę funkcję w tych 2 miejscach, w którym jest czyszczony ten interval. 
`clearInterval(this.animationInterval);`
`this.animationInterval = null;`

2023-03-22 21:09 UTC, Rubix98 commented on frontend/src/components/mainPage/scene/subcomponents/NavigationPanel.vue
> +                                this.icons[2].icon = "mdi-play";
W "computed" dodałbym jakąś funkcję np. playStopIcon, która zwraca ikonkę, którą chcemy tutaj zmienić. W przypadku, gdyby np zmieniła by się kolejność ikonek i ta ikonka by miała index 3 a nie 2, to mamy jedno miejsce gdzie trzeba to zmienić. No i jak w kodzie ktoś zobaczy `this.playStopIcon` to to więcej mówi niż `this.icons[2]` (ktoś by musiał sprawdzić jaka ikonka jest pod 2 indeksem)

2023-03-22 21:14 UTC, Rubix98 commented on frontend/src/components/mainPage/scene/subcomponents/NavigationPanel.vue
> +                    function (e) {
Dla spójności z pozostałą częścią kodu w projekcie proponuję używać funkcji strzałkowej `(e) => {...}` zamiast `function(e) {...}`.

2023-03-26 17:10 UTC, Rubix98 approved these changes

2023-03-26 17:12 UTC, merged